### ISSUE TITLE
500 server error when using the interface

### ISSUE THREAD

**Issue by deepakprabhakara** [oauth-io/oauthd-front#5]
This plugin tried to perform a GET against /api/providers/%7B%7B%20provider.provider%20%7D%7D/logo at some point and results in restify throwing an exception when trying to parse the url.

Stack trace:-
too few args to sprintf
code: InternalError
message: too few args to sprintf

Error: too few args to sprintf at jsSprintf (/usr/lib/node_modules/oauthd/node_modules/extsprintf/lib/extsprintf.js:71:11) at WError (/usr/lib/node_modules/oauthd/node_modules/verror/lib/verror.js:208:41) at HttpError (/usr/lib/node_modules/oauthd/node_modules/restify/lib/errors/http_error.js:44:12) at RestError (/usr/lib/node_modules/oauthd/node_modules/restify/lib/errors/rest_error.js:41:15) at new module.exports.(anonymous function) (/usr/lib/node_modules/oauthd/node_modules/restify/lib/errors/rest_error.js:86:19) at serveFileFromStats (/usr/lib/node_modules/oauthd/node_modules/restify/lib/plugins/static.js:34:18) at /usr/lib/node_modules/oauthd/node_modules/restify/lib/plugins/static.js:84:17 at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by deepakprabhakara** [comment]
Also this url - /api/providers/%7B%7B%20provider%20%7D%7D/logo
